---
- name: Get device facts
  hosts: dc1
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve device facts and save to file
      juniper.device.facts:        
        savedir: "{{ playbook_dir }}"
